/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "scribe_constants.h"

namespace scribe { namespace thrift {

const scribeConstants g_scribe_constants;

scribeConstants::scribeConstants() {
}

}} // namespace

